from __future__ import annotations

import csv
import html
from datetime import datetime, timedelta, timezone

from .db import DEMO_TODAY, ROOT, rows_as_dicts


REPORT_DIR = ROOT / "data" / "reports"


def _period(report_type: str):
    if report_type == "weekly":
        return DEMO_TODAY - timedelta(days=6), DEMO_TODAY
    if report_type == "inventory":
        return DEMO_TODAY, DEMO_TODAY
    return DEMO_TODAY, DEMO_TODAY


def _report_rows(connection, report_type: str, start, end) -> list[dict]:
    if report_type == "inventory":
        return rows_as_dicts(connection.execute(
            "SELECT sku, name, category, stock, reorder_point, units_30d, forecast_units, ROUND(stock * 14.0 / forecast_units, 1) cover_days FROM products ORDER BY cover_days"
        ).fetchall())
    return rows_as_dicts(connection.execute(
        "SELECT store, ROUND(SUM(revenue), 2) gross_revenue, SUM(orders) orders, ROUND(SUM(gross_margin), 2) gross_margin, ROUND(SUM(returns), 2) returns, ROUND((SUM(revenue)-SUM(returns))/SUM(orders), 2) avg_order_value FROM sales_daily WHERE sale_date BETWEEN ? AND ? GROUP BY store ORDER BY gross_revenue DESC",
        (start.isoformat(), end.isoformat()),
    ).fetchall())


def _render_html(report_type: str, start, end, rows: list[dict], generated_by: str) -> str:
    title = {"daily": "Daily Trading Brief", "weekly": "Weekly Operations Review", "inventory": "Inventory Exception Pack"}.get(report_type, "Operations Report")
    numeric_keys = [key for key in rows[0].keys() if key not in ("store", "sku", "name", "category")] if rows else []
    totals = {key: sum(float(row[key] or 0) for row in rows) for key in numeric_keys}
    headers = list(rows[0].keys()) if rows else []
    table_headers = "".join(f"<th>{html.escape(key.replace('_', ' ').title())}</th>" for key in headers)
    def display(key, value):
        if key in ("gross_revenue", "gross_margin", "returns", "avg_order_value"):
            return f"${float(value):,.2f}"
        if key in ("orders", "stock", "reorder_point", "units_30d", "forecast_units"):
            return f"{int(value):,}"
        if isinstance(value, float):
            return f"{value:,.1f}"
        return str(value)

    body = "".join("<tr>" + "".join(f"<td>{html.escape(display(key, value))}</td>" for key, value in row.items()) + "</tr>" for row in rows)
    cards = "".join(f"<div class='metric'><span>{html.escape(key.replace('_', ' ').title())}</span><strong>{html.escape(display(key, value))}</strong></div>" for key, value in list(totals.items())[:4])
    return f"""<!doctype html>
<html lang="en"><head><meta charset="utf-8"><title>{title}</title>
<style>
@page {{ size: A4 landscape; margin: 18mm; }}
* {{ box-sizing:border-box }} body {{ font:14px Inter,Arial,sans-serif;color:#182230;margin:0;background:#f6f8fb }}
.report {{ max-width:1120px;margin:28px auto;background:white;padding:42px;border:1px solid #dfe5ec;border-radius:18px }}
.brand {{ color:#5847e8;text-transform:uppercase;letter-spacing:.16em;font-size:11px;font-weight:800 }}
h1 {{ font-size:30px;margin:12px 0 6px }} .sub {{ color:#667085;margin-bottom:28px }}
.metrics {{ display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin:24px 0 }}
.metric {{ padding:16px;border:1px solid #e4e8ee;border-radius:12px }} .metric span {{ display:block;color:#667085;font-size:11px;text-transform:uppercase }} .metric strong {{ display:block;font-size:20px;margin-top:6px }}
table {{ width:100%;border-collapse:collapse;margin-top:24px }} th {{ text-align:left;background:#f1f3f7;color:#475467;font-size:11px;text-transform:uppercase;letter-spacing:.04em }} th,td {{ padding:12px;border-bottom:1px solid #e8ebf0 }} td:not(:first-child) {{ font-variant-numeric:tabular-nums }}
.footer {{ margin-top:28px;padding-top:16px;border-top:1px solid #e8ebf0;color:#7b8494;font-size:11px;display:flex;justify-content:space-between }}
</style></head><body><main class="report"><div class="brand">RelayOps · Northstar Retail Group</div><h1>{title}</h1><div class="sub">Reporting period {start:%d %b %Y} — {end:%d %b %Y} · Generated by {html.escape(generated_by)}</div><section class="metrics">{cards}</section><table><thead><tr>{table_headers}</tr></thead><tbody>{body}</tbody></table><div class="footer"><span>Source: governed SQLite analytical store</span><span>Run status: complete · {len(rows)} rows</span></div></main></body></html>"""


def generate_report(connection, report_type: str = "daily", commit: bool = True, generated_by: str = "Ops operator") -> list[dict]:
    if report_type not in ("daily", "weekly", "inventory"):
        raise ValueError("Unsupported report type")
    REPORT_DIR.mkdir(parents=True, exist_ok=True)
    start, end = _period(report_type)
    rows = _report_rows(connection, report_type, start, end)
    stamp = datetime.now(timezone.utc).strftime("%Y%m%d-%H%M%S-%f")
    prefix = f"{report_type}-{end.isoformat()}-{stamp}"
    artifacts = []
    csv_path = REPORT_DIR / f"{prefix}.csv"
    with csv_path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(rows[0].keys()) if rows else ["status"])
        writer.writeheader()
        if rows:
            writer.writerows(rows)
        else:
            writer.writerow({"status": "no data"})
    html_path = REPORT_DIR / f"{prefix}.html"
    html_path.write_text(_render_html(report_type, start, end, rows, generated_by), encoding="utf-8")
    created = datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z")
    title = {"daily": "Daily Trading Brief", "weekly": "Weekly Operations Review", "inventory": "Inventory Exception Pack"}[report_type]
    for output_path, output_format in ((html_path, "HTML"), (csv_path, "CSV")):
        cursor = connection.execute(
            "INSERT INTO reports(name, report_type, period_start, period_end, format, path, created_at, row_count, size_bytes, generated_by) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)",
            (title, report_type, start.isoformat(), end.isoformat(), output_format, output_path.name, created, len(rows), output_path.stat().st_size, generated_by),
        )
        artifacts.append({"id": cursor.lastrowid, "name": title, "report_type": report_type, "format": output_format, "path": output_path.name, "created_at": created, "row_count": len(rows), "size_bytes": output_path.stat().st_size, "generated_by": generated_by})
    connection.execute("UPDATE report_schedules SET last_run=? WHERE report_type=?", (created, report_type))
    connection.execute(
        "INSERT INTO audit_events(event_type, title, detail, actor, created_at) VALUES ('report', ?, ?, ?, ?)",
        (f"{title} generated", f"HTML and CSV artifacts created with {len(rows)} rows by {generated_by}.", generated_by, created),
    )
    if commit:
        connection.commit()
    return artifacts


def reports_payload(connection) -> dict:
    schedules = rows_as_dicts(connection.execute("SELECT * FROM report_schedules ORDER BY id").fetchall())
    for schedule in schedules:
        schedule["active"] = bool(schedule["active"])
    reports = rows_as_dicts(connection.execute("SELECT * FROM reports ORDER BY created_at DESC, id DESC LIMIT 30").fetchall())
    scheduled = connection.execute("SELECT COUNT(*) total,SUM(CASE WHEN status='success' THEN 1 ELSE 0 END) successful FROM scheduler_events WHERE job_type='report'").fetchone()
    scheduled_total = int(scheduled["total"] or 0)
    scheduler_success_rate = round(int(scheduled["successful"] or 0) / scheduled_total * 100, 1) if scheduled_total else None
    return {"schedules": schedules, "reports": reports, "metrics": {"active_schedules": sum(item["active"] for item in schedules), "generated_30d": len(reports), "scheduled_runs": scheduled_total, "scheduler_success_rate": scheduler_success_rate, "storage_bytes": sum(item["size_bytes"] for item in reports)}}
